# Generated by Django 3.2.7 on 2021-09-20 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.CharField(max_length=100, verbose_name='note text'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='note title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('PB', 'public'), ('PV', 'private')], default=True, max_length=10, verbose_name='visibility'),
        ),
    ]
