# Generated by Django 3.2.7 on 2021-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_title',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
