# Generated by Django 3.2.7 on 2021-09-22 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_auto_20210920_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
    ]
