# Generated by Django 3.2.7 on 2021-10-29 00:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='game_id')),
                ('name', models.TextField(unique=True, verbose_name='game_title')),
                ('description', models.TextField(verbose_name='game_description')),
                ('all_reviews_ratings', models.CharField(max_length=40)),
                ('all_reviews_count', models.CharField(max_length=30)),
                ('release_date', models.CharField(max_length=40)),
                ('developer', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=40)),
                ('poster_image', models.CharField(max_length=255, verbose_name='poster_image_path')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='review_id')),
                ('is_recommended', models.BooleanField(default=True)),
                ('posted_date', models.CharField(max_length=40)),
                ('text', models.TextField(verbose_name='review_text')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game', verbose_name='game_id')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='image_id')),
                ('image_path', models.CharField(max_length=255)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game', verbose_name='game_id')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(related_name='images', to='backend.Image'),
        ),
        migrations.AddField(
            model_name='game',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', to='backend.Review'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
