# Generated by Django 3.2.7 on 2021-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster_image',
            field=models.CharField(default='', max_length=255, verbose_name='poster_image_path'),
            preserve_default=False,
        ),
    ]
