# Generated by Django 3.2.8 on 2021-10-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='all_reviews',
            field=models.CharField(max_length=40, verbose_name='all_reviews'),
        ),
        migrations.AlterField(
            model_name='game',
            name='all_reviews_count',
            field=models.CharField(max_length=30, verbose_name='all_review_count'),
        ),
        migrations.AlterField(
            model_name='review',
            name='posted_date',
            field=models.CharField(max_length=40, verbose_name='posted_date'),
        ),
    ]
